<?php

declare(strict_types=1);

namespace App\Models;

use App\Domain\Audit\Concerns\Auditable;
use App\Enums\UserRole;
use Database\Factories\UserFactory;
use Filament\Models\Contracts\FilamentUser;
use Filament\Models\Contracts\HasName;
use Filament\Panel;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 * CRM Dermacells user model.
 *
 * Primary key is a UUID generated by Postgres (or Eloquent's HasUuids trait
 * as fallback in tests). Authentication is handled exclusively via Sanctum
 * tokens issued after OAuth (Google/Microsoft) — there is no password-based
 * login and no email verification flow (we use OAuth).
 *
 * @property string                       $id
 * @property string                       $email
 * @property string                       $full_name
 * @property \App\Enums\UserRole          $role
 * @property bool                         $can_sell
 * @property bool                         $is_active
 * @property bool                         $ai_enabled
 * @property \Illuminate\Support\Carbon|null $deactivated_at
 * @property \Illuminate\Support\Carbon|null $last_login_at
 * @property \Illuminate\Support\Carbon|null $email_verified_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 */
class User extends Authenticatable implements FilamentUser, HasName
{
    /** @use HasFactory<UserFactory> */
    use Auditable, HasApiTokens, HasFactory, HasUuids, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'email',
        'full_name',
        'role',
        'can_sell',
        'is_active',
        'ai_enabled',
        'deactivated_at',
        'last_login_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * Disable remember-me token persistence — users table has no
     * remember_token column (OAuth-only auth, no "remember me" flow).
     */
    public function getRememberTokenName(): string
    {
        return '';
    }

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'role'              => UserRole::class,
            'can_sell'          => 'boolean',
            'is_active'         => 'boolean',
            'ai_enabled'        => 'boolean',
            'deactivated_at'    => 'datetime',
            'last_login_at'     => 'datetime',
            'email_verified_at' => 'datetime',
        ];
    }

    /**
     * Filament FilamentUser contract — gate panel access by role.
     *
     * DEMO MODE — local env relaxation, production reverts.
     * In local/demo all three roles may enter /admin so role-scoped widgets
     * and sidebar visibility can be demonstrated. In production only Director
     * gets in (enforced here AND re-enforced by AdminAccessGate middleware).
     */
    public function canAccessPanel(Panel $panel): bool
    {
        if (app()->environment('local')) {
            return in_array($this->role, [
                UserRole::Director,
                UserRole::Distributor,
                UserRole::Seller,
            ], true);
        }

        return $this->role === UserRole::Director;
    }

    /**
     * Filament HasName contract — display name in topbar/avatar.
     */
    public function getFilamentName(): string
    {
        return $this->full_name ?? $this->email;
    }
}
