<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Xubio API request/response log — replay & forensic audit.
 *
 * Every HTTP call made by XubioClient is persisted here. The table is
 * append-only from the application perspective and pruned by
 * PruneXubioApiLogJob after 90 days (Xubio reconciliation window + buffer).
 *
 * id is BIGSERIAL: high-volume insert path; UUID overhead unnecessary.
 * request_id UUID: correlates a logical operation across multiple HTTP calls
 * (e.g., token refresh + emit invoice + fetch PDF). Generated by XubioClient.
 *
 * payload_json / response_json are jsonb so analysts can query them.
 *
 * No RLS — Director-only access via Filament page (which checks role server-side).
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE xubio_api_log (
                id              BIGSERIAL       PRIMARY KEY,
                request_id      UUID            NOT NULL,
                endpoint        TEXT            NOT NULL,
                method          TEXT            NOT NULL,
                payload_json    JSONB           NULL,
                response_json   JSONB           NULL,
                status_code     INTEGER         NULL,
                latency_ms      INTEGER         NULL,
                created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

                CONSTRAINT chk_xubio_api_log_status
                    CHECK (status_code IS NULL OR (status_code >= 100 AND status_code < 600)),

                CONSTRAINT chk_xubio_api_log_method
                    CHECK (method IN ('GET','POST','PUT','PATCH','DELETE'))
            )
        SQL);

        DB::statement('CREATE INDEX idx_xubio_api_log_created_at ON xubio_api_log (created_at)');
        DB::statement('CREATE INDEX idx_xubio_api_log_request_id ON xubio_api_log (request_id)');
        DB::statement('CREATE INDEX idx_xubio_api_log_endpoint ON xubio_api_log (endpoint)');

        DB::statement('GRANT SELECT, INSERT ON xubio_api_log TO app_role');
        DB::statement('GRANT SELECT ON xubio_api_log TO report_role');
        DB::statement('GRANT SELECT, INSERT, DELETE ON xubio_api_log TO worker_role');
        DB::statement('GRANT USAGE, SELECT ON SEQUENCE xubio_api_log_id_seq TO app_role');
        DB::statement('GRANT USAGE, SELECT ON SEQUENCE xubio_api_log_id_seq TO worker_role');
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS xubio_api_log CASCADE');
    }
};
