<?php

declare(strict_types=1);

namespace App\Filament\Resources;

use App\Filament\Resources\DistributorCommissionPaymentResource\Pages;
use App\Jobs\DistributorFinance\RecalculateDistributorAccountJob;
use App\Models\DistributorCommissionPayment;
use Filament\Forms;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

/**
 * Filament resource — DistributorCommissionPayment (§9.2)
 *
 * Read-mostly: Director views all commission payments across distributors.
 * The "Mark Paid" action allows recording that the Distributor has paid the Seller.
 * No create — rows are generated by ComputeMonthlyCommissionsJob.
 */
class DistributorCommissionPaymentResource extends Resource
{
    protected static ?string $model = DistributorCommissionPayment::class;

    protected static ?string $navigationIcon = 'heroicon-o-credit-card';

    protected static ?string $navigationLabel = 'Pagos de comisiones';

    protected static ?string $navigationGroup = 'Distribuidor Financiero';

    protected static ?int $navigationSort = 5;

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('distributor.full_name')
                    ->label('Distribuidor')
                    ->searchable()
                    ->sortable(),

                Tables\Columns\TextColumn::make('seller.full_name')
                    ->label('Vendedor')
                    ->searchable(),

                Tables\Columns\TextColumn::make('zone.name')
                    ->label('Zona'),

                Tables\Columns\TextColumn::make('period_month')
                    ->label('Período')
                    ->date('M Y')
                    ->sortable(),

                Tables\Columns\TextColumn::make('base_amount_amount')
                    ->label('Base')
                    ->numeric(decimalPlaces: 2),

                Tables\Columns\TextColumn::make('base_amount_currency')
                    ->label(''),

                Tables\Columns\TextColumn::make('commission_pct')
                    ->label('%')
                    ->formatStateUsing(fn (string $state) => number_format((float) $state * 100, 2) . '%'),

                Tables\Columns\TextColumn::make('commission_amount_amount')
                    ->label('Comisión')
                    ->numeric(decimalPlaces: 2),

                Tables\Columns\IconColumn::make('paid')
                    ->label('Pagado')
                    ->boolean()
                    ->trueIcon('heroicon-o-check-circle')
                    ->falseIcon('heroicon-o-x-circle'),

                Tables\Columns\TextColumn::make('paid_at')
                    ->label('Pagado el')
                    ->dateTime('d/m/Y'),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('distributor_id')
                    ->label('Distribuidor')
                    ->relationship('distributor', 'full_name'),

                Tables\Filters\TernaryFilter::make('paid')
                    ->label('Estado de pago'),
            ])
            ->actions([
                Tables\Actions\Action::make('mark_paid')
                    ->label('Marcar pagado')
                    ->icon('heroicon-o-check')
                    ->color('success')
                    ->visible(fn (DistributorCommissionPayment $record) => ! $record->paid)
                    ->requiresConfirmation()
                    ->form([
                        Forms\Components\TextInput::make('payment_reference')
                            ->label('Referencia de pago')
                            ->maxLength(500),
                    ])
                    ->action(function (DistributorCommissionPayment $record, array $data): void {
                        $record->paid              = true;
                        $record->paid_at           = now();
                        $record->paid_by           = auth()->id();
                        $record->payment_reference = $data['payment_reference'] ?? null;
                        $record->save();

                        RecalculateDistributorAccountJob::dispatch($record->distributor_id);

                        Notification::make()->success()->title('Pago registrado')->send();
                    }),
            ])
            ->defaultSort('period_month', 'desc');
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListDistributorCommissionPayments::route('/'),
        ];
    }

    public static function canCreate(): bool
    {
        return false;
    }
}
